export const SET_CARE_RECIPIENT = 'SET_CARE_RECIPIENT';
export const CARE_RECIPIENTS_RECEIVED = 'CARE_RECIPIENTS_RECEIVED';
export const EVENTS_RECEIVED = 'EVENTS_RECEIVED';
export const SELECT_EVENTS = 'SELECT_EVENTS';
